apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-node1
  namespace: devops-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible-node1
  template:
    metadata:
      labels:
        app: ansible-node1
    spec:
      containers:
      - name: ansible-node1
        image: ubuntu:20.04
        command: ["/bin/bash", "-c"]
        args:
          - apt update &&
            apt install -y openssh-server python3.9 python3-pip &&
            mkdir -p /var/run/sshd &&
            useradd -m -s /bin/bash ansibleuser &&
            echo "ansibleuser:ansibleuser" | chpasswd &&
            /usr/sbin/sshd -D
        ports:
        - containerPort: 22
        readinessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ansible-node1-ssh
  namespace: devops-lab
spec:
  selector:
    app: ansible-node1
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30222
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-node2
  namespace: devops-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible-node2
  template:
    metadata:
      labels:
        app: ansible-node2
    spec:
      containers:
      - name: ansible-node2
        image: ubuntu:20.04
        command: ["/bin/bash", "-c"]
        args:
          - apt update &&
            apt install -y openssh-server python3.9 python3-pip &&
            mkdir -p /var/run/sshd &&
            useradd -m -s /bin/bash ansibleuser &&
            echo "ansibleuser:ansibleuser" | chpasswd &&
            /usr/sbin/sshd -D
        ports:
        - containerPort: 22
        readinessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ansible-node2-ssh
  namespace: devops-lab
spec:
  selector:
    app: ansible-node2
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30223
  type: NodePort
