- name: Health check Ansible servers
  hosts: servers
  tasks:
    - name: Ping nodes
      ping:

    - name: Check uptime
      command: uptime
      register: uptime_result

    - debug:
        msg: "Uptime: {{ uptime_result.stdout }}"

    - name: Check running processes
      command: ps aux
      register: ps_result

    - debug:
        msg: "Processes: {{ ps_result.stdout_lines | select('search','ssh') | list }}"
