[servers]
ansible-node1 ansible_host=192.168.49.2 ansible_port=30222 ansible_user=ansibleuser ansible_password=ansibleuser ansible_python_interpreter=/usr/bin/python3
ansible-node2 ansible_host=192.168.49.2 ansible_port=30223 ansible_user=ansibleuser ansible_password=ansibleuser ansible_python_interpreter=/usr/bin/python3
